services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NITSAN\NsLicense\:
    resource: '../Classes/*'

  NITSAN\NsLicense\Setup:
    tags:
      - name: event.listener
        identifier: 'ns-license-check'
        method: 'executeOnSignal'
        event: TYPO3\CMS\Core\Package\Event\BeforePackageActivationEvent

  NITSAN\NsLicense\Controller\NsLicenseModuleController:
    arguments:
      $moduleTemplateFactory: '@TYPO3\CMS\Backend\Template\ModuleTemplateFactory'
      $requestFactory: '@TYPO3\CMS\Core\Http\RequestFactory'
      $nsLicenseRepository: '@NITSAN\NsLicense\Domain\Repository\NsLicenseRepository'
      $licenseService: '@NITSAN\NsLicense\Service\LicenseService'
      $catalogCacheService: '@NITSAN\NsLicense\Service\CatalogCacheService'
      $allLicensesService: '@NITSAN\NsLicense\Service\AllLicensesService'

  NITSAN\NsLicense\Domain\Repository\NsLicenseRepository:
    public: true
    
  NITSAN\NsLicense\Service\LicenseService:
    public: true

  NITSAN\NsLicense\Service\AllLicensesCacheService:
    public: true

  NITSAN\NsLicense\Service\AllLicensesService:
    public: true

  NITSAN\NsLicense\Controller\AllLicensesAjaxController:
    public: true
